### ISSUE TITLE
Typo on the https://kookma.github.io/TW5-GitHub-Saver/#Quick%20Setup

### ISSUE THREAD

**Issue by cblte** [kookma/TW5-GitHub-Saver#4]
Hello, 

the tiddler https://kookma.github.io/TW5-GitHub-Saver/#Quick%20Setup contains a typo in the first URL.

`From https://tiddlywiki.comI downloaded an empty edition and rename the empty.html downloaded to index.html`
should be
`From https://tiddlywiki.com downloaded an empty edition and rename the empty.html downloaded to index.html`

There is an upper case i (I) at the end of the first URL.

**Comment by kookma** [comment]
@cblte - corrected. Sorry I have forgotten this!
