### ISSUE TITLE
SyncAdaptor version?

### ISSUE THREAD

**Issue by linonetwo** [kookma/TW5-GitHub-Saver#5]
I'm using nodejs wiki, which will produce small git history, and human-readable diff. But I can't use nodejs wiki on the mobile.

So I think if there can be a sync adaptor that saves changed individual tiddler to github, this can be solved.

**Comment by kookma** [comment]
Hi @linonetwo - I did not quite understand what is the question! but I know you have some great plugin to directly save to github?
do you proposing to use them here? or you are asking add a sync adapter here!

Side note: I see your activity on TW and your wikis, codes, plugins, but I don't see to introduce them in community (e.g talk tiddlywiki). I think there are many users for your great additions!

**Comment by linonetwo** [comment]
Oh, I wrote too much about the benefit of SyncAdaptor in this issue, which may confuse you. 

Yes, I was asking to add a sync adapter here, do you think it is possible? But maybe you don't need a syncAdaptor yourself, because you are using HTML wiki. Maybe I will try write one (next year :P )

P.S. I was mostly writing TiddlyGit for the past year, which is an App wrapping nodejs wiki, so normal people can setup nodejs wiki easily. I didn't write much plugins these days, but I will introduce them in "talk tiddlywiki" if I write plugins again!

**Comment by kookma** [comment]
> Yes, I was asking to add a sync adapter here, do you think it is possible? But maybe you don't need a syncAdaptor yourself, because you are using HTML wiki. Maybe I will try write one (next year :P )

I think it is a great idea! I use single html, but I would be happy to add your solution for Node.JS version!
I think we can also use GitHub Action with your TiddlyGit!
